alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gs='git status'
alias gl='git log --graph --pretty=format:"%an: %s%C(yellow)%d%Creset %Cgreen(%cr)%Creset %Cblue %h %Creset" --date=relative'
alias gcd='git checkout development'
alias gpo='git pull origin'
alias gps='git push origin'
alias gsh='git show HEAD'
alias gh='cat ~/.bash_aliases'
alias work='source env/bin/activate'
